export enum TILE_STATUS {
    AVAILABLE = 'AVAILABLE',
    PLAYER1 = 'PLAYER1',
    PLAYER2 = 'PLAYER2'
}

export enum PLAYERS {
    PLAYER1 = 'PLAYER1',
    PLAYER2 = 'PLAYER2'
}

export enum GAME_ACTIONS {
    PLAYER1 = 'PLAYER1',
    PLAYER2 = 'PLAYER2',
    RESTART = 'RESTART'
}
